### ISSUE TITLE
Simple form for support 

### ISSUE THREAD

**Issue by uzaif313** [GetJobber/recurring_select#116]
Hi,
I have used below code for work with simple_form_for and recurring_select

`
<%= f.input :recurrence_rule, as: :select_recurring %>
`
above code is throw  `NoMethodError at /events/new
undefined method 'select_recurring' for nil:NilClass`  error
how can i user recurring_select with simple_form_for

**Comment by ast3150** [comment]
For me it seems to work well with simple_form. I have created my form like this:

```
<%= simple_form_for @mymodel, html: { class: 'form-horizontal'} do |m| %>
    <%= m.select_recurring :recurring_rules %>
<% end %>
```
